"""Unit tests for AgenticCoach.chat_stream (PR C).

This is the async generator that powers /api/ai/chat/stream. It wraps
the LangGraph agent's astream_events(version='v2') and filters to four
event types the UI cares about: token / tool_call / done / error.

We mock the underlying agent's astream_events rather than spinning up a
real LangGraph runtime — the unit under test is the filter + footer
assembly, not LangGraph itself.
"""

from __future__ import annotations

import asyncio
from unittest.mock import AsyncMock, MagicMock

from backend.agentic_coach import AgenticCoach


def _chunk(text):
    """Stand-in for a LangChain AIMessageChunk. .content can be a
    list of {type:'text', text:...} blocks (Gemini-via-LangChain) or
    a plain str (most other providers). chat_stream's _chunk_text
    helper flattens both."""
    c = MagicMock()
    c.content = text
    return c


def _stream_event(event: str, name: str = "", chunk=None, output=None, _input=None):
    """Build one astream_events frame matching the v2 shape we care
    about. Production code only reads `.event`, `.name`, `.data.chunk`."""
    return {
        "event": event,
        "name": name,
        "data": {
            **({"chunk": chunk} if chunk is not None else {}),
            **({"output": output} if output is not None else {}),
            **({"input": _input} if _input is not None else {}),
        },
    }


async def _fake_stream(events):
    """Async generator that replays a list of pre-built events."""
    for ev in events:
        yield ev


def _make_coach_with_stream(tmp_chat_db, events):
    coach = AgenticCoach(db_path=tmp_chat_db, skip_api_probe=True)
    coach._ensure_agent = AsyncMock()
    coach._agent = MagicMock()
    coach._agent.astream_events = MagicMock(return_value=_fake_stream(events))
    coach._last_provider = "gemini"
    return coach


def _collect(gen):
    """Drain an async generator into a list via asyncio.run.
    Per project convention (test_personal_coach_mcp.py / PR #67):
    we avoid pytest-asyncio and use asyncio.run at call sites."""

    async def _drain():
        return [ev async for ev in gen]

    return asyncio.run(_drain())


class TestChatStreamHappyPath:
    def test_emits_tokens_then_footer_then_done(self, tmp_chat_db):
        events = [
            _stream_event("on_chat_model_stream", chunk=_chunk("Hello")),
            _stream_event("on_chat_model_stream", chunk=_chunk(" world")),
            _stream_event("on_chat_model_end"),  # not surfaced
        ]
        coach = _make_coach_with_stream(tmp_chat_db, events)

        result = _collect(
            coach.chat_stream(user_input="hi", thread_id="t")
        )

        # tokens forwarded, then footer, then done
        assert result[0] == {"type": "token", "content": "Hello"}
        assert result[1] == {"type": "token", "content": " world"}
        # Footer carries the model name (resolved via get_provider_model_name)
        assert result[2]["type"] == "token"
        assert "Generated by" in result[2]["content"]
        assert result[3] == {"type": "done"}

    def test_tool_call_event_surfaced(self, tmp_chat_db):
        events = [
            _stream_event("on_chat_model_stream", chunk=_chunk("Let me check.")),
            _stream_event("on_tool_start", name="get_readiness"),
            _stream_event("on_tool_end", name="get_readiness"),  # not surfaced
            _stream_event("on_chat_model_stream", chunk=_chunk(" Green light today.")),
        ]
        coach = _make_coach_with_stream(tmp_chat_db, events)

        result = _collect(
            coach.chat_stream(user_input="how am i", thread_id="t")
        )

        tool_events = [r for r in result if r["type"] == "tool_call"]
        assert tool_events == [{"type": "tool_call", "name": "get_readiness"}]


class TestChatStreamContentHandling:
    def test_block_list_content_flattened(self, tmp_chat_db):
        """Gemini emits content as [{type:'text', text:'...'}] blocks.
        chat_stream must flatten to plain str — otherwise the SSE
        wire payload ships a JSON list and frontend renders raw."""
        block_chunk = _chunk([
            {"type": "text", "text": "Hello "},
            {"type": "text", "text": "world"},
            {"type": "tool_use", "id": "no_text_key"},  # silently dropped
        ])
        coach = _make_coach_with_stream(
            tmp_chat_db,
            [_stream_event("on_chat_model_stream", chunk=block_chunk)],
        )

        result = _collect(
            coach.chat_stream(user_input="hi", thread_id="t")
        )
        assert result[0] == {"type": "token", "content": "Hello world"}

    def test_empty_chunk_skipped(self, tmp_chat_db):
        """Some stream events carry metadata-only chunks with empty
        content. Emitting a {type:'token', content:''} would be noisy
        on the wire — chat_stream filters them out."""
        coach = _make_coach_with_stream(
            tmp_chat_db,
            [
                _stream_event("on_chat_model_stream", chunk=_chunk("")),
                _stream_event("on_chat_model_stream", chunk=_chunk("real")),
            ],
        )

        result = _collect(
            coach.chat_stream(user_input="hi", thread_id="t")
        )
        token_events = [r for r in result if r["type"] == "token" and "Generated by" not in r["content"]]
        assert token_events == [{"type": "token", "content": "real"}]


class TestChatStreamErrorPath:
    def test_exception_in_underlying_stream_becomes_error_event(self, tmp_chat_db):
        """If LangGraph (rate limit, network, etc.) raises mid-stream
        we catch and convert to {type:'error'}. The frontend then
        decides whether to retry."""
        async def _exploding():
            yield _stream_event("on_chat_model_stream", chunk=_chunk("partial"))
            raise RuntimeError("429 rate limit hit")

        coach = AgenticCoach(db_path=tmp_chat_db, skip_api_probe=True)
        coach._ensure_agent = AsyncMock()
        coach._agent = MagicMock()
        coach._agent.astream_events = MagicMock(return_value=_exploding())

        result = _collect(
            coach.chat_stream(user_input="hi", thread_id="t")
        )

        # Token streamed before exception is preserved; then the error
        # event terminates the stream (no footer / done after error).
        assert result[0] == {"type": "token", "content": "partial"}
        assert result[-1]["type"] == "error"
        assert "429" in result[-1]["message"]
        # No 'done' should follow an error.
        assert not any(r.get("type") == "done" for r in result)
